### ISSUE TITLE
Display proper message for insufficient quota

### ISSUE THREAD

**Issue by carlrobertoh** [carlrobertoh/ChatGPT#2]
Replace `Something went wrong. Please try again later.` with more meaningful message.

OpenAI response(429):
```
{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
```

**Comment by mustafacakirogluK24** [comment]
I am encountering the exact same issue. Is it normal to "exceed" my quota even though its my first time sending a message to chatgpt?

**Comment by carlrobertoh** [comment]
@mustafacakirogluK24 Hey, I think it depends when did you create your account.

`As a free trial user, you receive an initial credit of $18 that expires after three months.` https://help.openai.com/en/articles/6643435-how-do-i-get-more-tokens-or-increase-my-monthly-usage-limits

**Comment by mustafacakirogluK24** [comment]
@carlrobertoh hey, thanks for the answers both here and in the jetbrains marketplace. I tried the curl request you sent and as we thought, it was the insufficient quota error. Weird cuz I opened that account just a month ago and didn't use any other 3rd party stuff so my initial credit should still be there. Anyways nothing you can do as this is an openai issue. I removed my marketplace review since we already have an open issue here, no need to clutter the marketplace reviews.

**Comment by carlrobertoh** [comment]
@mustafacakirogluK24 Thanks for raising concern. Unfortunately there's nothing more I can do on my side. I suggest contacting OpenAI directly, upgrading your plan or open a new account (if possible).
